spring:

  liquibase:
    changeLog: "classpath:db/changelog/db.changelog-master.yaml"
    default-schema: "game"
    liquibase-schema: "public"

  datasource:
    url: 'jdbc:postgresql://localhost:5432/connect-four?currentSchema=game'
    username: mois
    password: 12345

  management:
    endpoints:
      web:
        exposure:
          include=health,info,shutdown:
